# Generated by Django 5.1.5 on 2025-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'WhatsApp Message', 'verbose_name_plural': 'WhatsApp Messages'},
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='content',
            field=models.TextField(help_text='The content of the WhatsApp message'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='receiver',
            field=models.CharField(help_text="The receiver's WhatsApp number (e.g., whatsapp:+0987654321)", max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sender',
            field=models.CharField(help_text="The sender's WhatsApp number (e.g., whatsapp:+1234567890)", max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', help_text='The current status of the message', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the message was created'),
        ),
    ]
